const PAGES_PATH = {
	LANDING: '/',
	MENU: '/Menu',
	ADD_MENU: '/AddMenu',
	NEWS: '/News',
	ADD_NEWS: 'Add-News',
	BANNER: '/Banner',
	ADD_BANNER: '/Add-Banner',
	UPLOAD_VIDEO: '/Upload-Video',
	VIDEO: '/Video',
	UPLOAD_GALLERY_IMAGE: '/Upload-Gallery-Image',
	CREATE_IMAGE: '/Image',
	GALLERY_IMAGE: '/gallery-images',
	ADD_CSR: '/Add-Corporate-Responsibility',
	CSR: '/CorporateResponsibility',
	ADD_FORM_DATA: '/Add-Form-Data',
	FORM_DATA: '/List-Form-Data',
	ADD_CONTACT_BRANCH: '/Add-Contact-Branch',
	CONTACT_BRANCH: '/ListContactBranch',
	RECENTLY_APPROVED: '/Recently-Approved-List',
	ADD_RECENTLY_APPROVED: '/Add-Recently-Approved',
	PRACTICE_NOTES: '/Practice-Notes-List',
	ADD_PRACTICE_NOTES: '/Add-Practice-Notes',
	PUBLICATIONS: '/Publications-List',
	ADD_PUBLICATIONS: '/Add-publication',
	TENDERS: '/Tender-List',
	ADD_TENDERS: '/AddTender',
	USER_FEEDBACKS: '/User-FeedBacks',
	WHATS_NEWS: '/MyWhatsNew',
	ADD_WHATS_NEWS: '/AddMyWhatsNews',
	MY_NEWS_PRINT: '/MyNewsPrint',
	FAQ: '/FAQ',
	ADD_FAQ: '/AddFAQ',
	NOTICE_BOARD: '/List-Public-Board',
	ADD_NOTICE_BOARD: '/Add-Notice-Board',
	PUBLIC_MEETING: '/List-Public-Meetings',
	ADD_PUBLIC_MEETING: '/Add-Public-Meetings',
	TAX_CODE: '/List-Tax-Item-Code',
	ADD_TAX_CODE: '/Add-Tax-Item-Code',
	TEAM_DATA: '/List-Team-Data',
	ADD_TEAM_DATA: '/Add-Team-Data',
	SETTINGS: '/setting',
	LOGIN: '/login'
};

export default PAGES_PATH;
