export * from './AddBanner'
export * from './AddCorResp'
export * from './AddNews'
export * from './AddWhatNew'
export * from './Banner'
export * from './CreateImage'
export * from './CreateVideo'
export * from './ImpLinks'
export * from './Menu'
export * from './News'
export * from './NoticeBoard'
export * from './RecentlyApproved'
export * from './UploadGalleryImage'
export * from './UserFeedback'

